### ISSUE TITLE
Image assets need implementing

### ISSUE THREAD

**Issue by MitchElbourne** [craftapplied/energeiaworks#26]
Home page: Graphic map
Our Focus: all sections
Employers: All four bottom sections
Events: Top section circular image replace
About: Top section circular image replace
Blog: Top section circular image replace

**Comment by darrenbarklie** [comment]
@NghiH - Do you have an estimate on rollout of these graphic devices?  Happy to use stock imagery and progressively enhance if it gets us to launch quicker.  Let's discuss in this thread.
