### ISSUE TITLE
Global: Navigation 

### ISSUE THREAD

**Issue by darrenbarklie** [craftapplied/energeiaworks#51]
Conditionally render menu/close states of toggle button
Fix styling of Contact
Remove blue color from Contact (always looks active)

**Comment by darrenbarklie** [comment]
![image](https://user-images.githubusercontent.com/3026261/51530188-508b1100-1e32-11e9-90cb-0afa4a99e0bf.png)

**Comment by MitchElbourne** [comment]
![screenshot 2019-01-24 at 09 20 23](https://user-images.githubusercontent.com/43572803/51668072-52cba780-1fb9-11e9-8f62-cc1ed5f59f6f.png)
