### ISSUE TITLE
Homepage - Focus sectors content

### ISSUE THREAD

**Issue by darrenbarklie** [craftapplied/energeiaworks#52]
Update Focus modules content - lift from website

![image](https://user-images.githubusercontent.com/3026261/51530803-af04bf00-1e33-11e9-9d3a-d6e787bd8fd8.png)

**Comment by darrenbarklie** [comment]
Read More links - where do these go?  Link them up.

**Comment by MitchElbourne** [comment]
![screenshot 2019-01-23 at 18 37 22](https://user-images.githubusercontent.com/43572803/51628828-f37c8180-1f3d-11e9-981a-102d6f703101.png)
