### ISSUE TITLE
Homepage - Event middot

### ISSUE THREAD

**Issue by darrenbarklie** [craftapplied/energeiaworks#58]
Check sizing, HTML character type, position relative to vertically align
![image](https://user-images.githubusercontent.com/3026261/51531878-8f22ca80-1e36-11e9-892f-3b3fd26e57c3.png)

**Comment by darrenbarklie** [comment]
![image](https://user-images.githubusercontent.com/3026261/51531866-8af6ad00-1e36-11e9-9a0c-f247793f8fc1.png)

**Comment by MitchElbourne** [comment]
![screen shot 2019-01-22 at 15 21 04](https://user-images.githubusercontent.com/43572803/51545201-6102b200-1e59-11e9-8e8b-ed01104c830a.png)

**Comment by MitchElbourne** [comment]
@darrenbarklie
